version: '3.8'

services:
  php-fpm:
    image: ghcr.io/dessybin/php_wintercms:latest
    ports:
      - 9900:80
    volumes:
      - my-volume:/var/www/html
      - my-storage:/var/www/html/storage
      - my-config-storage:/var/www/html/config
      - my-plugins-base:/var/www/html/plugin
      - my-themes-base:/var/www/html/themes
    depends_on:
      - db

  apache-httpd:
    image: ghcr.io/dessybin/apache_wintercms:latest
    volumes:
      - my-volume:/var/www/html
      - my-storage:/var/www/html/storage
      - my-config-storage:/var/www/html/config
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: "winter"
      POSTGRES_PASSWORD: example
    volumes:
      - ../../db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    my-volume:
    my-storage:
    my-config-storage:
    my-plugins-base:
    my-themes-base: