name: DOCKER IMAGE CI FOR GHCR

on: push

jobs:
    build_and_publish_apache:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: apache-conf
        steps:
            - uses: actions/checkout@v4
            - name: Build and push the image
              run: |
                docker login --username dessybin --password ${{ secrets.GH_PAT }} ghcr.io
            - name: Pull latest images
              run: docker pull ghcr.io/dessybin/apache_wintercms:latest || true
            - name: Images list
              run: docker images
            - name: BUILD DOCKER
              run: docker build -f ./apache.dockerfile . --tag ghcr.io/dessybin/apache_wintercms:latest
            - name: DOCKER PUSH
              run: docker push ghcr.io/dessybin/apache_wintercms:latest\
            - name: Logout
              run: |
                docker logout ghcr.io
    build_and_publish_php:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Build and push the image
            run: |
              docker login --username dessybin --password ${{ secrets.GH_PAT }} ghcr.io
          - name: Pull latest images
            run: docker pull ghcr.io/dessybin/php_wintercms:latest || true
          - name: Images list
            run: docker images
          - name: BUILD DOCKER
            run: docker build -f ./php/php.dockerfile . --tag ghcr.io/dessybin/php_wintercms:latest
          - name: DOCKER PUSH
            run: docker push ghcr.io/dessybin/php_wintercms:latest\
          - name: Logout
            run: |
              docker logout ghcr.io