name: DOCKER IMAGE CI FOR GHCR

on: push

jobs:
    scanning:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v2
          id: cache-db
          with:
              path: ~/.symfony/cache
              key: db
        - uses: symfonycorp/security-checker-action@v5
        - name: Lint PHP files
          uses: overtrue/phplint@main
          with:
            path: .
            options: --exclude=vendor
    tests:
      runs-on: ubuntu-latest
      steps:
        - name: PHPUnit Tests
          uses: php-actions/phpunit@master
          env:
            TEST_NAME: Dessy WinterCMS Tests
          with:
            version: 9.6
            bootstrap: vendor/autoload.php
            configuration: phpunit.xml
            args: --coverage-text
    build_and_publish_apache:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: login GHCR
              run: |
                docker login --username dessybin --password ${{ secrets.GH_PAT }} ghcr.io
            - name: BUILD DOCKER
              uses: docker/build-push-action@v5
              with:
                context: .
                file: .docker/apache-conf/apache.dockerfile
                push: true
                tags: ghcr.io/dessybin/apache_wintercms:latest
                cache-from: type=registry,ref=ghcr.io/dessybin/apache_wintercms:buildcache
                cache-to: type=registry,ref=ghcr.io/dessybin/apache_wintercms:buildcache,mode=max
            - name: Logout
              run: |
               docker logout ghcr.io
    build_and_publish_php:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: login GHCR
            run: |
              docker login --username dessybin --password ${{ secrets.GH_PAT }} ghcr.io
          - name: BUILD DOCKER
            uses: docker/build-push-action@v5
            with:
              context: .
              file: .docker/php/php.dockerfile
              push: true
              tags: ghcr.io/dessybin/php_wintercms:latest
              cache-from: type=registry,ref=ghcr.io/dessybin/php_wintercms:buildcache
              cache-to: type=registry,ref=ghcr.io/dessybin/php_wintercms:buildcache,mode=max
          - name: Logout
            run: |
              docker logout ghcr.io
