name: DOCKER IMAGE CI FOR GHCR

on: push
permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
  issues: write
jobs:

    lint-php-check:
      runs-on: ubuntu-latest
      steps:
        - name: Lint PHP files
          uses: overtrue/phplint@main
          with:
            path: .
            options: --exclude=vendor
    
    tests:
      needs: lint-php-check
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: PHPUnit Tests
          uses: nathanheffley/laravel-phpunit-action@master
    
    dep-analyze:
      needs: [lint-php-check, tests]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v2
          id: cache-db
          with:
              path: ~/.symfony/cache
              key: db
        - uses: symfonycorp/security-checker-action@v5
    
    sast-step:
      needs: [lint-php-check, tests, dep-analyze]
      runs-on: ubuntu-latest
      steps:
        - name: BEARER scan
          uses: bearer/bearer-action@v2
          with:
            format: sarif
            output: results.sarif
            exit-code: 0
        - name: Upload Bearer scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: 'results.sarif'

    build_and_publish_apache:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: login GHCR
          run: |
            docker login --username dessybin --password ${{ secrets.GH_PAT }} ghcr.io
        - name: BUILD DOCKER
          uses: docker/build-push-action@v5
          with:
            context: .
            file: .docker/apache-conf/apache.dockerfile
            push: true
            tags: ghcr.io/dessybin/apache_wintercms:latest
            cache-from: type=registry,ref=ghcr.io/dessybin/apache_wintercms:buildcache
            cache-to: type=registry,ref=ghcr.io/dessybin/apache_wintercms:buildcache,mode=max
        - name: Logout
          run: |
            docker logout ghcr.io

    container-check-apache:
      runs-on: ubuntu-latest
      needs: build_and_publish_apache
      steps:
        - name: login GHCR
          run: |
            docker login --username dessybin --password ${{ secrets.GH_PAT }} ghcr.io
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'ghcr.io/dessybin/apache_wintercms:latest'
            format: 'sarif'
            output: 'trivy-results.sarif'
          env:
            TRIVY_USERNAME: dessybin
            TRIVY_PASSWORD: ${{ secrets.GH_PAT }}
        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: 'trivy-results.sarif'  
        - name: Logout
          run: |
            docker logout ghcr.io

    build_and_publish_php:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: login GHCR
          run: |
            docker login --username dessybin --password ${{ secrets.GH_PAT }} ghcr.io
        - name: BUILD DOCKER
          uses: docker/build-push-action@v5
          with:
            context: .
            file: .docker/php/php.dockerfile
            push: true
            tags: ghcr.io/dessybin/php_wintercms:latest
            cache-from: type=registry,ref=ghcr.io/dessybin/php_wintercms:buildcache
            cache-to: type=registry,ref=ghcr.io/dessybin/php_wintercms:buildcache,mode=max
        - name: Logout
          run: |
            docker logout ghcr.io

    container-check-php:
      runs-on: ubuntu-latest
      needs: build_and_publish_php
      steps:
        - name: login GHCR
          run: |
            docker login --username dessybin --password ${{ secrets.GH_PAT }} ghcr.io          
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'ghcr.io/dessybin/php_wintercms:latest'
            format: 'sarif'
            output: 'trivy-results.sarif'
          env:
            TRIVY_USERNAME: dessybin
            TRIVY_PASSWORD: ${{ secrets.GH_PAT }}
        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: 'trivy-results.sarif'        

    deploy:
      needs: [build_and_publish_php, build_and_publish_apache] 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4          
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            passphrase: ${{ secrets.SSH_PASSPH }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: /home/deployuser/app/.docker/startup.sh

    dast_owasp_zap:
      needs: deploy
      runs-on: ubuntu-latest
      steps:
        - name: ZAP Scan
          uses: zaproxy/action-full-scan@v0.10.0
          with:
            target: 'http://87.249.53.20/'